package com.tuplataforma.core.application.errors;

public enum ErrorCode {
    PERMISSION_DENIED,
    TENANT_SUSPENDED,
    MODULE_DISABLED,
    QUOTA_EXCEEDED,
    PLAN_RESTRICTION,
    VEHICLE_NOT_FOUND,
    FLEET_NOT_FOUND,
    INVALID_LICENSE_PLATE,
    VEHICLE_ALREADY_ASSIGNED,
    CROSS_TENANT_ASSIGNMENT,
    CONCURRENT_MODIFICATION,
    UNEXPECTED_ERROR
}

